# -*- coding: utf-8 -*-
# Une ligne par Element, façon concurrent : description + "100% matches the reference".
REFDESC = {
# --- personnages ---
"SamBefore":"Sam before, a man in his forties, clean, upright, hands with NO ink on them. A man who talks: he performs small things for his family, narrates his own failures while they happen, laughs at himself, touches people as he passes them. Loose in the shoulders, nothing guarded. 100% matches the reference.",
"Sam":"Sam two years later, a month of badly trimmed beard, ten kilos heavier, grey under the eyes. Two years without speaking — not sullen, emptied. He moves through his own house like a guest, shoulders forward, eyes down and to the side. Every gesture is finished; none is explained. 100% matches the reference.",
"SamSDF":"The vagrant — Sam in disguise, and playing him well. Slower, stiller, older in the joints; the cold has genuinely got into him. He does not perform kindness: he asks for something small, receives it, gives back more than he took, and states it flatly. He never watches anyone walk away while they can still see him. 100% matches the reference.",
"Mender":"The coat only — a long dark coat covered edge to edge in dense handwriting worn to texture. NEVER a face, never eyes, never identifiable. Seen from behind or passing through frame. 100% matches the reference.",
"Maeve":"Maeve, alive — dry, fast, affectionate and entirely unsentimental. She does not soften her voice for anyone; what she wants she asks for plainly, and once. Her tenderness arrives as instruction, never as comfort. 100% matches the reference.",
"MaeveIll":"Maeve in hospital, forty, the illness has taken her body and left the voice and the impatience intact. She spends what is left on being understood, not on being reassuring. Not frightened, and not brave about it either — out of time and aware of it. 100% matches the reference.",
"Nora":"Nora, fifteen, long dark brown unwashed hair, grey-green eyes, pale olive skin gone colourless, bitten lips, heavy lids over grey hollows, thin build. Running on empty: grief has made her polite and absent — she answers, she says thank you, and none of it reaches her face. She goes very still before anything shows. NOTHING RED ON HER. 100% matches the reference.",
"NoraBefore":"Nora at thirteen, entirely unguarded. She interrupts, she leans on people, she laughs at her father's jokes before he finishes them. Her happiness is loud, physical, and costs her nothing. 100% matches the reference.",
"Milo":"Milo, eight, the only one in the house who still says things out loud. He has not learned to be careful around grief, so he asks, and keeps asking. Watchful pale grey-blue eyes that go to his sister's face first. 100% matches the reference.",
"MiloBefore":"Milo at six, made of momentum. He arrives at speed, collides with legs, is picked up, is off again. He does not listen to whole sentences. 100% matches the reference.",
"Anna":"Anna, the old neighbour — a woman who has buried people and keeps the stove lit. Warm without softness, quick and practical in the hands, slow and careful in the eyes. She does not comfort: she pours the tea and waits. She will cry mid-sentence and go on in the same steady voice, and never wipe her face. Swollen crooked fingers. 100% matches the reference.",
"AnnaYoung":"Anna thirty years earlier, forty-eight — the same woman: practical hands, straight back, no drama offered to anyone. Everything that breaks in her breaks inward and without sound, until the one moment it does not. Never a victim in any frame. 100% matches the reference.",
"Kolya11":"Anna's son, eleven, gravely ill in a hospital bed, too small for it, mouth slightly open, a strand of hair stuck to his forehead. 100% matches the reference.",
"Kolya2":"A small boy of about two, in a courtyard, thirty years ago. 100% matches the reference.",
"WardDoctor":"A ward doctor of the period, plain cloth cap, no insignia, no badge, no legible text on anything he wears. 100% matches the reference.",
"YoungMother":"A young woman of about twenty-five, thirty years ago. 100% matches the reference.",
"YoungMotherHospital":"The same young woman two years earlier, twenty-three and heavily pregnant, on a rolling hospital gurney. 100% matches the reference.",
"Mei":"Mei, fifty-eight, who runs the restaurant — brisk, busy, entirely unmystified, and still running it while this happens. What she passes on she passes on the way she would pass on a phone number: practical, low, half over her shoulder, already moving. Dark green apron stained at the hip. 100% matches the reference.",
"Asha":"Asha, fifty-two, upright, deliberate, economical. She listens longer than is comfortable before saying anything, and when she speaks it is short and settled. Her hands are still when she talks. Warmth in her comes out as attention, not as smiling. 100% matches the reference.",
"Fatiha":"Fatiha, sixty-six, and everything she says goes through her hands first. Quick, warm, interrupting, laughing at the edge of serious things. She touches the arm of whoever she talks to, mentions what broke her the way you mention the weather, and moves on. 100% matches the reference.",
# --- objets ---
"AnnaDrawing":"An old pencil drawing of a BACK covered in writing, on yellowed foxed paper gone soft as cloth from being folded and unfolded, two deep fold lines that will not lie flat, the graphite worn silver where thumbs have passed. No legible letter anywhere. 100% matches the reference.",
"MotherRing":"A plain worn wedding ring, thin, unpolished, no stone, no engraving legible. 100% matches the reference.",
# --- lieux ---
"Kitchen":"The family kitchen — warm domestic wood and cream-and-blue crockery, morning light through glass. NO RED anywhere in the room. 100% matches the reference.",
"Quay":"The fishing quay at golden hour, worn timber, wet stone, open water behind. 100% matches the reference.",
"KidsBedroom":"The children's bedroom, warm evening. 100% matches the reference.",
"HospitalRoom":"A hospital room — sea-green tiling, water-green monitors, no red anywhere, no legible signage. 100% matches the reference.",
"HospitalCorridor":"A hospital corridor — sea-green tiling to half height, green signage, deep perspective, no legible text. 100% matches the reference.",
"AnnaKitchen":"Anna's kitchen — the stove lit behind its grate, one bulb under an enamel shade, the corners of the room in warm dark. Worn oilcloth rubbed white at the elbows. The flame stays AMBER, never a saturated ember, no red anywhere. 100% matches the reference.",
"AnnaKitchenPast":"Anna's Russian kitchen thirty years ago, at night — one bulb, the cast-iron stove dead and packed with cold ash. No Cyrillic character, no digit, no poster anywhere. 100% matches the reference.",
"Restaurant":"Mei's restaurant — amber lanterns, green tablecloths, a green fish tank. No red anywhere, no legible signage. 100% matches the reference.",
"NoraBedroom":"Nora's bedroom and the landing outside it, grey and underexposed, one narrow sodium band under the door. 100% matches the reference.",
"BackGallery":"The back gallery at night under sodium, wet concrete, iron rail. 100% matches the reference.",
"Bathroom":"A small bathroom, tiled, a mirror over the basin. 100% matches the reference.",
"LibraryCorridor":"A school library corridor, flat grey afternoon through high windows, shelving in depth. No legible book title anywhere. 100% matches the reference.",
"NightBus":"The night bus — neon inside, sodium outside, no red, no legible destination display. 100% matches the reference.",
"BusShelter":"The bus shelter at the end of the world, a single sodium cone in the dark, wet ground, no legible signage. 100% matches the reference.",
"RedHouseExterior":"The last house of a poor terraced street, wooden-fronted, deep dark red gone chalky, neighbours grey and blank, wet black road. THE ONLY RED IN THE WORLD OUTSIDE. 100% matches the reference.",
"RedHouseInterior":"One downstairs room of an old cottage, its cracked plaster written over from skirting to a man's height in dense dark red looping cursive; wide worn boards, a written staircase, a small window with black night behind. The strokes form no characters, in no language, nowhere legible. 100% matches the reference.",
"RussianHospitalCorridor":"A Soviet-era hospital corridor, sea-green tiling to half height, tube lights, deep perspective. No Cyrillic character, no digit, no sign anywhere. 100% matches the reference.",
"RussianHospitalWard":"A Soviet-era common ward, iron beds in a row, sea-green tiling to half height. No legible text anywhere. 100% matches the reference.",
"RussianNightStreet":"A street between concrete blocks at night under mercury light, thirty years ago. No Cyrillic character, no plate, no poster. 100% matches the reference.",
"RussianCourtyard":"A courtyard between apartment blocks at night under mercury light, a bench, bare ground. No Cyrillic character, no sign anywhere. 100% matches the reference.",
}
